midexampasigado/urls.py
from django.contrib import admin
from django.urls import path, include
from votes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votes/', include('votes.urls')),
]

votes/urls.py
from django.urls import path
from . import views
app_name = 'votes'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('candidate_create/', views.candidate_create, name = 'candidate_create'),
    path('position_create/', views.position_create, name = 'position_create'),
    path('<int:candidate_id>/', views.candidate_detail, name='candidate_detail'),
    path('<int:candidate_id>/candidate_update', views.candidate_update, name='candidate_update'),
    path('<int:candidate_id>/vote', views.vote, name='vote'),
    
]

votes/models.py
from django.db import models

# Create your models here.

class Position(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

class Candidate(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    birthdate = models.DateTimeField("Birthdate")
    platform = models.TextField()

    def __str__(self):
        return self.lastname + ", " + self.firstname

class Vote(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    vote_datetime = models.DateTimeField("Date Voted", auto_now_add=True)

    def __str__(self):
        return self.vote_datetime

votes/forms.py
from django.forms import ModelForm 
from .models import Candidate, Position, Vote

class CandidateModelForm(ModelForm):
    class Meta:
        model = Candidate
        exclude = ['id']

class PositionModelForm(ModelForm):
    class Meta:
        model = Position
        exclude = ['id']

class VoteModelForm(ModelForm):
    class Meta:
        model = Vote
        exclude = ['id']

votes/views.py
from django.shortcuts import render, redirect
from .models import Position, Vote, Candidate
from .forms import PositionModelForm, VoteModelForm, CandidateModelForm

# Create your views here.

def index(request):
    context = {}
    context['candidates'] = Candidate.objects.all().order_by('position')
    return render(request, 'index.html', context)

def candidate_create(request):
    context = {}
    context['form'] = CandidateModelForm()
    
    if request.method == 'POST':
        form = CandidateModelForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('/votes/')
        else: 
            return render(request, 'candidate_create.html', context)
    else:
        return render(request, 'candidate_create.html', context)

def candidate_detail(request, candidate_id):
    context = {}
    context['candidate'] = Candidate.objects.get(id=candidate_id)
    return render(request, 'candidate_detail.html', context)

def candidate_update(request, candidate_id):
    context = {}
    post = Candidate.objects.get(id=candidate_id)
    context['id'] = candidate_id

    if request.method == 'POST':
        form = CandidateModelForm(request.POST, instance=post)

        if form.is_valid():
            form.save()
            return redirect('/votes/' + str(candidate_id))
        else:
            context['form']  = form
            return render(request, 'candidate_update.html', context)

    else:
        context['form'] = CandidateModelForm(instance=post)
    return render(request, 'candidate_update.html', context)

def position_create(request):
    context = {}
    context['form'] = PositionModelForm()
    
    if request.method == 'POST':
        form = PositionModelForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('/votes/')
        else:
            return render(request, 'position_create.html', context)
    else:
        return render(request, 'position_create.html', context)

def vote(request, candidate_id):
    print("here" + str(candidate_id))
    x = Vote(candidate = Candidate.objects.get(id=candidate_id))
    x.save()
    return redirect('/votes/')

votes/templates/base.html
{% load static %}

<html>
    <head>
        <title>
            {% block head %}
            
            {% endblock head %}
        </title>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        
        {% block styles %}
        {% endblock styles %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href='{% url 'votes:index' %}'> Candidates </a>

            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href='{% url 'votes:position_create' %}'>Create a position</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url 'votes:candidate_create' %}'>Add a candidate</a>
                </li>
            </ul>
        </nav>

        <div class="container">
            {% block body %}
                123456
            {% endblock body %}
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

        {% block scripts %}

        {% endblock %}
    </body>
</html>

votes/templates/candidate_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
 

{% block head %}
    Add New Candidate
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:candidate_create'%}" method="POST">
        {% csrf_token %}

        <div class="row mt-5 mb-3"> 
                <h1> Add a new candidate </h1>
        </div>

        {{ form|crispy }}

        
        <input type="submit" class="btn btn-primary" value="Add">
        <a href='{% url 'votes:index' %}'>
                <button type="button" class="btn btn-outline-danger"> Cancel</button>
        </a>
    </form>
{% endblock body %}

votes/templates/candidate_detail.html
{% extends 'base.html' %}

{% block head %}
{% endblock head %}

{% block body %}
        <a href='{% url 'votes:index' %}'>
                <button type="button" class="btn btn-outline-light mt-5 text-dark"> &lt  Go back to candidates</button>
        </a>

        <div class="card mt-3">
                <div class="card-body  p-5">
                        <div class="row mb-1"> 
                                <h1> {{ candidate.lastname }}, {{ candidate.firstname }} 
                                
                                <span class="ml-3">
                                        <a href='{% url 'votes:vote' candidate.id %}'>
                                                <button type="button" class="btn btn-primary">
                                                        Vote <span class="badge badge-light ml-2"> {{ candidate.vote_set.count }}</span>
                                                </button>
                                        </a>
                                </span>
                        </div>

                        <div class="row"> 
                                <p> As <span class="font-weight-bold"> {{ candidate.position }} </span> </p> 
                        </div>
                        <div class="row"> 
                                <small> Born 
                                        <span> {{ candidate.birthdate }} </span> 
                                </small>
                        </div>
                        <div class="row mt-2"> 
                                <a href='{% url 'votes:candidate_update' candidate.id %}'> 
                                        <span class="badge badge-dark">Update Details</span>
                                </a>
                        </div>
                        <div class="row"> 
                                <div class="card bg-light mb-3 mt-5 w-100">
                                        <div class="card-header font-weight-bold" style="font-size: 15; letter-spacing: 3">PLATFORM</div>
                                        <div class="card-body">
                                                <p class="card-text">{{ candidate.platform }}</p>
                                        </div>
                                </div>

                                <p class="text-justify mt-5 mb-5"> <p>
                        </div>
                </div>
        </div>
        
{% endblock body %}

votes/templates/candidate_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    The Update Page
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:candidate_update' form.instance.id %}" method="POST">
        {% csrf_token %}

        <div class="row mt-5 mb-3"> 
                <h1> Edit "{{ form.lastname.value }}, {{ form.firstname.value }}" </h1>
        </div>

             {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Update">
        <a href="{% url 'votes:candidate_detail' id %}">
                <button type="button" class="btn btn-outline-danger"> Cancel</button>
        </a>
    </form>
{% endblock body %}

votes/templates/index.html
{% extends "base.html" %} 

{% block head %}
    Candidates List
{% endblock head %}

{% block body %}
    <div class="row mt-5 mb-5">
        <h2 class="ml-3"> All Candidates 
            <a href='{% url 'votes:position_create' %}'> <span class="btn btn-outline-primary ml-3">Create a position</span> </a>
            <a href='{% url 'votes:candidate_create' %}'> <span class="btn btn-outline-primary ml-3">Add a new candidate</span> </a> 
        </h2>
    </div>
    <div class="list-group">
        {% for candidate in candidates %}
            <a href="{% url 'votes:candidate_detail' candidate.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ candidate.lastname }}, {{candidate.firstname}}</h5>
                    <small> {{ candidate.vote_set.count}} vote(s) </small>
                </div>

                <p class="mb-1"> {{ candidate.position }} </p>
            </a>

        {% endfor %}
    </div>
{% endblock body %}

votes/templates/position_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    Add New Position
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:position_create'%}" method="POST">
        {% csrf_token %}

        <div class="row mt-5 mb-3"> 
                <h1> Create a new Position </h1>
        </div>

        {{ form|crispy }}

        <input type="submit" class="btn btn-primary" value="Add">
        <a href='{% url 'votes:index' %}'>
                <button type="button" class="btn btn-outline-danger"> Cancel </button>
        </a>
    </form>
{% endblock body %}